### ISSUE TITLE
安装时报错，安卓platform提示color.xml已存在

### ISSUE THREAD

**Issue by LeeJunhui** [giantss/cordova-plugin-ImagePicker#1]
RT,这个错误我请了安卓的同事分析了下，暂时找不出原因

**Comment by giantss** [comment]
你是不是少写了一个s，应该是colors.xml
解决方法
1，注释掉plugin.xml中注释掉 ` <source-file src="src/android/res/values/colors.xml" target-dir="res/values"/>`大概在264行左右。
2，在 `  <config-file target="AndroidManifest.xml" parent="/manifest">`结束标签下面 大概在174行下（同级）添加如下代码：
` <config-file target="res/values/colors.xml" parent="/*">
            <color name="theme_body">#cc22292c</color>
            <color name="black">#000000</color>
            <color name="status_bar">#303135</color>
            <color name="top_bar">#9f556061</color>
            <color name="transparent">#00000000</color>
        </config-file>`
3，删除 `src/android/res/values/`目录下的`colors.xml`（不删也可以）
4，重新build

**Comment by LeeJunhui** [comment]
不好意思才来回答，按照@giantss的思路，解决了该问题。

**Comment by giantss** [comment]
嗯，看来你不太关注自己的消息
