### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. 

### ISSUE THREAD

**Issue by UTSOURCE** [giantss/cordova-plugin-ImagePicker#103]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

此插件使用了UIWebView 吗?

**Comment by andy27149** [comment]
同问

**Comment by lovelyelfpop** [comment]
没有
