### ISSUE TITLE
关于修改包名的建议

### ISSUE THREAD

**Issue by HoldSkill** [giantss/cordova-plugin-ImagePicker#11]
感谢您的开源！
![image](https://user-images.githubusercontent.com/25190239/30678941-4c042562-9ec8-11e7-814d-24934640117a.png)
请问这一点是否可以在````add plugin````的时候在末尾添加参数来实现呢？这样显得自动化一些，哈哈哈

**Comment by giantss** [comment]
好的，有时间我看看，同时欢迎 Fork and Pull requests
