### ISSUE TITLE
android 7.0华为P9勾选图片还是闪退。。

### ISSUE THREAD

**Issue by a81584944** [giantss/cordova-plugin-ImagePicker#12]
platform: android7.0
已按照readme中写的尝试了所有的改动，还是闪退。。
且本身机器中没有装barcodescanner 所以也就没有patient-barcodescanner.gradle

**Comment by HarleyTan** [comment]
小米note也是选图闪退。
小米note拍照不闪退。因为没有动态申请权限吗？

版本是Android6.0.1,MUIUI8.5

**Comment by HarleyTan** [comment]
应该是加权限，permissions.READ_EXTERNAL_STORAGE

楼主也试试

**Comment by HarleyTan** [comment]
哦，还是不行，问题是这样的：
预览图片没问题，在点“选择”的时候，就会肯亏然后返回了初始的页面

已经确认了具备READ_EXTERNAL_STORAGE权限

**Comment by HarleyTan** [comment]
把crosswalk卸载了（rm）也不行呢

**Comment by giantss** [comment]
把报错信息 发上来我看看

**Comment by HarleyTan** [comment]
@giantss 电脑太破了，跑Android Studio好几次都卡死了，调试没反应。

刚买了个新电脑，在路上了，等打了断点调试，给您反馈

chrome的console无输出
