### ISSUE TITLE
自定义主题

### ISSUE THREAD

**Issue by jjljyn** [giantss/cordova-plugin-ImagePicker#13]
你好，
非常感谢你能开源这个插件，我才接触cordova，正发愁怎么同时实现多选图片和拍照功能就找到这个插件了。
我有个问题，怎么样能够自定义主题呢？我的APP顶栏不是黑色背景，以后也可能会换颜色，希望能指点一下。

**Comment by GuoDapeng** [comment]
自定义主题的话需要修改插件原生代码的部分，因为这个插件打开的是一个原生都view。
