### ISSUE TITLE
gif的转换问题

### ISSUE THREAD

**Issue by li405744717** [giantss/cordova-plugin-ImagePicker#17]
[[PHImageManager defaultManager] requestImageDataForAsset:asset options:option resultHandler: .. 即使参数PHAsset是个gif内容
但是返回的还是一个jpg图片的NSData
可以参考:
先设置gif的temp位置(url),然后用
- (void)writeDataForAssetResource:(PHAssetResource *)resource
                           toFile:(NSURL *)fileURL
                          options:(nullable PHAssetResourceRequestOptions *)options
                completionHandler:(void(^)(NSError *__nullable error))completionHandler;方法生成temp的gif图片,再获取url的nsdata.从而拿到gif图片的真是nsdata
还有..最后sendPluginResult也需要返回这个gif的temp位置..

**Comment by giantss** [comment]
嗯 目前返回的所有图片地址都转成jpg了
