### ISSUE TITLE
我装了这个插件之后，jmessage-phonegap-plugin这个插件失效了

### ISSUE THREAD

**Issue by zc422** [giantss/cordova-plugin-ImagePicker#19]
我装了这个插件之后，jmessage-phonegap-plugin这个插件失效了

**Comment by giantss** [comment]
...,这个应该不会吧，我项目中使用了极光推送的官方插件没事的。

**Comment by zc422** [comment]
我重装了下就好了，但是好像返回的是缓存路径，不是真实路径。怎么获取到真实路径呢

**Comment by giantss** [comment]
你是指ios吗？

**Comment by zc422** [comment]
我是android的。返回的图片不是真实路径 是data/data/

**Comment by giantss** [comment]
发一个选图返回的完整路径

**Comment by zc422** [comment]
![qq 20171124170229](https://user-images.githubusercontent.com/28388644/33202944-49a6c880-d139-11e7-8a81-2e30709812f6.png)

**Comment by giantss** [comment]
什么手机 android版本是多少

**Comment by zc422** [comment]
华为荣耀7  安卓版本6.0

**Comment by giantss** [comment]
返回路径不对的问题 我还是第一次遇到有人反映，还有其他测试手机吗？试试看

**Comment by zc422** [comment]
这样啊，那我试试其他手机0.0

**Comment by giantss** [comment]
嗯，这个插件 还是有不少人使用的 没看他们反映过 我自己也一直在用没遇到过

**Comment by zc422** [comment]
恩恩 好的 谢谢啦
