### ISSUE TITLE
关于用法

### ISSUE THREAD

**Issue by LeeJunhui** [giantss/cordova-plugin-ImagePicker#2]
我直接根据wiki里的用法
`ImagePicker.getPictrues()`
然后cordova运行起来报错，错误信息是ImagePicker对象未定义。
然后我又尝试了下
`window.plugins.ImagePicker`还是不行

**Comment by LeeJunhui** [comment]
经过本人测试，需要在plugins文件夹中的`ios.json`和`android.json`添加以下代码：
`
        "cordova-plugin-ImagePicker":{
            "PACKAGE_NAME": ""
        },
`
然后执行`cordova build --device`，然后我发现在iOS上面XCode会报`THREAD WARNING: ['ImagePicker'] took '64.115967' ms. Plugin should use a background thread.`，经过一番google后，在iOS里的`imagePickerMain.m`文件中的`getPictures`方法加入
`
[self.commandDelegate runInBackground:^{}];
`
其中，最后一步的`  [self.viewController presentViewController:imagePickerVc animated:YES completion:nil];`用下列代码替代即可
`
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.viewController presentViewController:imagePickerVc animated:YES completion:nil];
        });
`

**Comment by lovelyelfpop** [comment]
@LeeJunhui ios.json和android.json是自动生成的

每次build cordova项目的时候都将以下目录和文件删除后再build：
对于安卓，删除 cordova/plugins/android.json文件和 cordova/platforms/android文件夹

对于ios，删除 cordova/plugins/ios.json文件和 cordova/platforms/ios文件夹

如果是 phonegap，那就 cordova 改成  phonegap

主要是这些情况下
1、不是cordova plugin add命令添加插件，而是把插件文件夹放到cordova/plugins/下面；
2、改了cordova/plugins/下面某个插件的代码
如果不删除就build，插件的改动就应用不上去
3、某一次build出错，如果不删除，之后的build还是会错

**Comment by giantss** [comment]
@lovelyelfpop 正解

**Comment by LeeJunhui** [comment]
@lovelyelfpop 我在`Cordova`中导入楼主的插件是用的
`cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git`
然后Cordova环境就会报一个错，那个错在上一个issue里已经得到了解决了。后来在代码里引用ImagePicker的时候呢，发现了不能识别`ImagePicker`这个对象，然后几经搜索与思考，在`ios.json`与`android.json`里添加了对应的插件描述，发现就可以识别了。我想了一下，可能是添加插件在安卓那里报错了，所以导致`ios.json`与`android.json`没有引用对应的插件。所以这块个人感觉楼主如果更新了源码的话，应该是可以得到解决的。然后由于`Cordova`自身的限制，基本上耗时的操作都得在后台线程去执行，否则前台界面很容易卡死。

**Comment by giantss** [comment]
@LeeJunhui 你这个错误我第一个issues已经给出解决方案，如果存在这样的问题自己修改插件配置文件即可。每个人使用的插件多样化，不能适用于每个人，你这个“文件已经存在的“错误，使用者中就你遇到了。
