### ISSUE TITLE
请问修改了配置允许选择视频后，为什么选择了视频没有返回值呢？

### ISSUE THREAD

**Issue by houruicheng** [giantss/cordova-plugin-ImagePicker#20]
在imagePickerMain.m文件中修改了_enablePickingVideo为true，是不插件返回那里就只返回了图片的url？
还有我想支持视频也能多选，这里面可以修改吗？麻烦指教下，给一个思路，刚接触OC没多久，希望大神给个方案，谢谢！

**Comment by giantss** [comment]
目前只支持只返回图片Url。
![image](https://user-images.githubusercontent.com/13778798/33310380-5556dc3a-d45c-11e7-85b7-a0f7d0d85e92.png)
这个位置是cordova返回选中的图片地址。另外如果你要扩展多选视频的功能的话你可以去
![image](https://user-images.githubusercontent.com/13778798/33310435-8ec54e84-d45c-11e7-98e2-0e7670a3c602.png)这两位源码提供者的源码地址找一些方案，自己扩展一下，功能源码里面应该支持，只是没有开发出来。

**Comment by houruicheng** [comment]
@giantss 感谢您的回复！好的我去学习下！

**Comment by giantss** [comment]
加油😄
