### ISSUE TITLE
App crash when select image with xiaomi5.

### ISSUE THREAD

**Issue by woodman250** [giantss/cordova-plugin-ImagePicker#25]
App crash when select image with xiaomi5.

**Comment by GuoDapeng** [comment]
有没有安装其他插件？

https://github.com/giantss/cordova-plugin-ImagePicker#插件选图闪退问题

**Comment by GuoDapeng** [comment]
如果可能的话。希望能帮忙验证这个问题。

单独建立一个全新的 cordova 项目，测试插件是否可用。

**Comment by woodman250** [comment]
测试发现，和cordova-plugin-crosswalk-webview插件冲突导致app闪退。
cordova-plugin-crosswalk-webview的使用还是很广泛的，望尽快解决。

**Comment by giantss** [comment]
这个插件两个作者都没用过，如果你解决了 欢迎PR
