### ISSUE TITLE
IOS11原图上传标注和实际上传相差巨大。

### ISSUE THREAD

**Issue by a81584944** [giantss/cordova-plugin-ImagePicker#26]
IOS11原图上传的时候显示1.7M，但是通过请求抓包发现上传了11M还多。。。。

**Comment by giantss** [comment]
你测试图片实际大小是多少吗

**Comment by a81584944** [comment]
@giantss 实际大小没有拿到数据，是iphone6s拍摄的，之前上传的都是2M左右吧，3个月前的版本没有这个问题，还有我设置的option的值 输出的应该也不会那么大。

**Comment by giantss** [comment]
你非常确定上传的11M全是这一张图片吗

**Comment by a81584944** [comment]
@giantss 对啊。我只上传一张。。目前都是在ios11的设备下发现的。假如不勾选原图 则图像很小，然后就是模糊不清。假如勾选了原图上传就是11m左右一张。。想问下这个option设置的width和height是否有用的

**Comment by giantss** [comment]
当然有用，width，height值越大图片大小就越大
