### ISSUE TITLE
通过$cordovaFile.copyFile()拷贝图片时提示 NOT_FOUND_ERR

### ISSUE THREAD

**Issue by layne-shi** [giantss/cordova-plugin-ImagePicker#29]
我想将选择的图片拷到别的地方去，通过些插件获取到的图片地址是：/data/user/0/io.ionic.starter/cacheCompressHelper/IMG_20171228_095307.jpeg，在使用$cordovaFile.copyFile()时，无论是直接用这个地址还是在这个地址前加了file://，都无法拷贝，返回NOT_FOUND_ERR。
请问我该怎么办？

**Comment by giantss** [comment]
图片地址显示和上传是否正常

**Comment by layne-shi** [comment]
可以正常显示。
我是想把它拷到手机存储中的一个文件夹下（需求就是这样T_T），我是用的$cordovaFile.copyFile()命令。
我用它拷camera插件返回的图片时是可以拷贝成功的。
通过camera插件返回的图片地址是：file:///storage/emulated/0/Pictures/IMG_20180102_120107.jpg

跪求解！！！





在 2017-12-29 15:01:24，"giantss" <notifications@github.com> 写道：


图片地址显示和上传是否正常

**Comment by giantss** [comment]
这个我也不清楚哎，麻烦自己调试一下把。
