### ISSUE TITLE
cordova run android报错，运行不了。。。

### ISSUE THREAD

**Issue by F5F5** [giantss/cordova-plugin-ImagePicker#3]
![image](https://user-images.githubusercontent.com/15978277/29010227-52b82f28-7b5c-11e7-92cf-73b8347f0149.png)

**Comment by F5F5** [comment]
@giantss 大神帮忙看一下

**Comment by giantss** [comment]
@F5F5 这个错误是因为你cordova build的时候使用到Source Compatibility 是 1.6，1.6中不支持diamond运算，另外我又更新了一下插件，修复了一些问题 你需要先remove然后在add，然后看  README.md 中android注意事项
你可以用android studio导入项目然后按照下图操作 然后再不同项目
![5f953ef6-050b-4408-88d7-e6cd7f53fc4b](https://user-images.githubusercontent.com/13778798/29011058-89d301da-7b62-11e7-9a6e-27d4c86499fb.png)
![8668ef67-d113-4d8b-8f08-4eeafae88f5d](https://user-images.githubusercontent.com/13778798/29011073-bd921920-7b62-11e7-877b-f5978ead782e.png)

**Comment by F5F5** [comment]
![image](https://user-images.githubusercontent.com/15978277/29013033-a113ee08-7b72-11e7-91fb-5ba35ccf861c.png)
@giantss 大佬，又报其他错了，貌似@color/theme_body这个东西有问题。。。

**Comment by giantss** [comment]
漏了 一段代码  已经修复
