### ISSUE TITLE
android运行失败

### ISSUE THREAD

**Issue by SAOSO** [giantss/cordova-plugin-ImagePicker#30]
PT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/caizepeng/Library/Android/sdk/build-tools/25.0.0/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 FAILED

BUILD FAILED

Total time: 14.694 secs

安装插件后执行cordova-plugin-android报错了

**Comment by giantss** [comment]
什么叫执行cordova-plugin-android
