### ISSUE TITLE
调用报错 

### ISSUE THREAD

**Issue by duckls** [giantss/cordova-plugin-ImagePicker#31]
`
declare  let  cordova :any;
@Component({
})

    cordova.plugins.ImagePicker.getPictures(function (result) {

      alert(result);

    }, function (err) {

      alert(err);

    }, {maximumImagesCount: 9, width: 1920, height: 1440, quality: 100});

`
楼主，这样调用报错， 我自定义自己的插件这样调用没有问问题

**Comment by giantss** [comment]
环境 报错信息发来看看

**Comment by duckls** [comment]
@giantss 没有报错 点击没反应

**Comment by giantss** [comment]
环境

**Comment by a81584944** [comment]
Your system information:

Cordova CLI: 6.2.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v5.3.0
Xcode version: Xcode 9.1 Build version 9B55

**Comment by a81584944** [comment]
同点击没反应了。xcode  会报出一个
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull objectForKey:]: unrecognized selector sent to instance 0x1b2876580

**Comment by a81584944** [comment]
这个问题我发现只要把 { maximumImagesCount : 9, width : 720, height : 720, quality : 80 } 带上就能调用起来了，但是回到之前的问题，我这边发现我不管这个option怎么设置 上传的图片都是原图，而且是那种10多兆的原图。。直接拿返回到前端的字符串类型的地址 上传到云端 发现有10多兆

**Comment by giantss** [comment]
@a81584944 
![image](https://user-images.githubusercontent.com/13778798/34701246-04e5068c-f522-11e7-9f4e-adee7bb946e7.png)
#26
