### ISSUE TITLE
Error: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').

### ISSUE THREAD

**Issue by houruicheng** [giantss/cordova-plugin-ImagePicker#32]
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
E:\WorkSpace\IONIC-Pro\web-one\platforms\android\build\intermediates\manifests\full\armv7\debug\AndroidManifest.xml:45:28-43: AAPT: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').

E:\WorkSpace\IONIC-Pro\web-one\platforms\android\build\intermediates\manifests\full\armv7\debug\AndroidManifest.xml:40: error: Error: No resource found that matches the given name (at 'theme' with value '@style/AppTheme').

**Comment by houruicheng** [comment]
按照说明复制了xml里的文件，build又提示了这个错误

**Comment by GuoDapeng** [comment]
建议单独建立一个cordova项目验证一下。我觉得这个错误应该是和某个插件一起产生的问题。
或者将 Android 版本规定为 6.3.0 试试。
```
cordova platform add android@6.3.0
```

**Comment by lovelyelfpop** [comment]
更新至最新的插件看看
