### ISSUE TITLE
UIImage 转 nsdata的问题，图片变大或者被压缩

### ISSUE THREAD

**Issue by FWiner** [giantss/cordova-plugin-ImagePicker#40]
调试了很久这句代码，同样的图片，imageData的值差距很大，会变化
imageData = UIImagePNGRepresentation(currentImage);

**Comment by giantss** [comment]
能再说详细点么？具体是怎么个差距很大

**Comment by lovelyelfpop** [comment]
的确是旧版的问题，原图jpg，压缩的NSData是UIImage转换成Png得到的，的确可能会比原图大很多。
新版已修改，选原图也有效果了。
