### ISSUE TITLE
 你把我的Pull request合并了，然后又把我的代码revert了

### ISSUE THREAD

**Issue by songlipeng2003** [giantss/cordova-plugin-ImagePicker#41]
你把我的Pull request合并了，然后又把我的代码revert了，所以最新的代码ios的图片还是有问题

**Comment by a81584944** [comment]
@songlipeng2003 我fork下来合了你改的代码算是暂时解决问题了。。研究了下貌似也没啥问题，谢谢啊

**Comment by songlipeng2003** [comment]
我们已经在正式环境使用，目前没有发现问题

**Comment by GuoDapeng** [comment]
我现在没时间解决这个让我不是很明白的两个方法，各有利弊，但是我需要你的那个 PR 里面的方法，我担心你在做其他方面的改进时会混到这次 PR 里。所以我建立了新的分支存放了你提交的 PR。我是这么想的，我最近事情很多，所以很抱歉不能很好的解决这个问题。很感谢你这么关注这件事情。

**Comment by GuoDapeng** [comment]
我一定给出一个既能选择不牺牲画质又能选择更高效率的方法。

**Comment by giantss** [comment]
#58

**Comment by lovelyelfpop** [comment]
@songlipeng2003 用最新的插件看看
