### ISSUE TITLE
直接选择图片app重启（？）

### ISSUE THREAD

**Issue by DiWangYinQing** [giantss/cordova-plugin-ImagePicker#42]
你好，我安装https://github.com/wymsee/cordova-imagePicker.git这个插件没有问题，可以正确运行。但是安装的你的插件后直接选择图片app会重启，放大图片在选择则没有问题，拍照也没有问题，请问是哪里出了问题呢？

**Comment by GuoDapeng** [comment]
可以看一下日志，一般是 com.android.support:support-v4 的版本不合适。

**Comment by DiWangYinQing** [comment]
好的，谢谢，我重新创了项目，确实是插件有冲突

**Comment by GuoDapeng** [comment]
不客气，有事常来玩。
