### ISSUE TITLE
点击相册内的图片后闪退，返回后图片都不见了

### ISSUE THREAD

**Issue by EditFly** [giantss/cordova-plugin-ImagePicker#47]
在ImageDataSource.java 中修改 

        //回调接口，通知图片数据准备完成
        ImagePicker.getInstance().setImageFolders(imageFolders);
        loadedListener.onImagesLoaded(imageFolders);
        if(loaderManager.getLoader(LOADER_ALL)!=null){
            loaderManager.destroyLoader(LOADER_ALL);
          }
问题解决

**Comment by giantss** [comment]
你的这种情况在你哪里，每次都会出现吗？

**Comment by EditFly** [comment]
对的 可以看我的简书  https://www.jianshu.com/p/d84ac72c386c

**Comment by giantss** [comment]
我刚才试过了你描述的情况，这是我写的一个简单的[demo](https://github.com/giantss/cordova-plugin-ImagePicker/tree/master/example/cordova/ImagePickerDemo)，我这里并没有出现你描述的选中图片会闪退 返回后图片不见了的情况

**Comment by EditFly** [comment]
可能是android版本不一样吧

**Comment by giantss** [comment]
能提供一下你的 使用环境么
