### ISSUE TITLE
返回键没有处理，会闪退

### ISSUE THREAD

**Issue by EditFly** [giantss/cordova-plugin-ImagePicker#48]
解决办法：ImageGridActivity.java中
@Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_BACK && event.getRepeatCount() == 0) {
      // 按下BACK，同时没有重复
      //Log.d(WZLOG, "onKeyDown()");
    }
    return super.onKeyDown(keyCode, event);
  }
  @Override
  public void onBackPressed() {
    //Log.d(WZLOG, "onBackPressed()");
    super.onBackPressed();
  }

**Comment by giantss** [comment]
这个操作也可以在js中监听返回键事件实现。
