### ISSUE TITLE
app闪退

### ISSUE THREAD

**Issue by congyingww** [giantss/cordova-plugin-ImagePicker#49]
上个项目用完全没问题，昨天新项目安装这个插件后 打开app就闪退 ，remove插件后app就能正常运行

**Comment by giantss** [comment]
环境提供下

**Comment by giantss** [comment]
这是我写的一个简单的[demo](https://github.com/giantss/cordova-plugin-ImagePicker/tree/master/example/cordova/ImagePickerDemo) 你可以参考一下， 随便描述一下你闪退的过程 如果能有错误日志更好

**Comment by GuoDapeng** [comment]
直接把 cordova 项目放插件里面了？

**Comment by GuoDapeng** [comment]
单独建立一个库不好吗？

**Comment by giantss** [comment]
@GuoDapeng 提议很好，已经单独创建了一个demo库并修改。下次回复issue的时候麻烦在指定位置回复（比如你这个回复应该出现在我提交的记录下去回复），不要在随便找一个issue回复与该issue无关的问题。🙏

**Comment by congyingww** [comment]
问题已解决，插件恢复使用。
原因可能是：您的demo放在了插件中，移出后插件正常，app不再闪退

**Comment by giantss** [comment]
@congyingww demo不是2天前放进去的吗？你使用的时候还没有放demo

**Comment by congyingww** [comment]
难道是安装方式问题，我前几天一直用的 cordova plugin add cordova-plugin-imagepicker-plus 安装。

今天用的git : cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git 安装就好用了
