### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Mr-Anonymous** [giantss/cordova-plugin-ImagePicker#52]
Does this plugin require any additional English translation? Or does it automatically use the language in phone? The screenshot images in ReadMe shows in Chinese I think. All of my users are English so when they select photos from their album, will the texts be in English (as in their default phone language) or Chinese?

Thank you.

**Comment by Mr-Anonymous** [comment]
For example, I noticed the camera option that shows in Image Picker shows like this. How can I change the language to use English only?
<img width="94" alt="camera-image-picker" src="https://user-images.githubusercontent.com/8770270/39353763-4568850e-4a26-11e8-9dfb-742084afa3fb.png">

**Comment by giantss** [comment]
![wechatimg108](https://user-images.githubusercontent.com/13778798/39390033-a466b922-4ac1-11e8-99d9-de515f2555b7.jpeg)

If you are in a hurry, you can first modify the location of the above map to English.

**Comment by Mr-Anonymous** [comment]
That helps. I will do that. I would need to release my App by next weekend and I will edit that file. Thank you for pointing in the right direction.
