### ISSUE TITLE
Event when Image Selection in Cancelled from Album

### ISSUE THREAD

**Issue by Mr-Anonymous** [giantss/cordova-plugin-ImagePicker#53]
I noticed that when you go to the Album and then press Cancel without selecting an image, an error is not returned when no image is obtained. This is the code I have:

```
ImagePicker.getPictures(function(results) {
   console.log(results);
}, function (error) {
    console.log('Error: ' + error);
    alert("Unable to obtain pictures");
}, options); 
```

In the above, when the image selection is cancelled, I thought I should get the `Unable to obtain pictures` alert but that doesn't work. Neither the success nor the error method is triggered when cancelled. This is the same in both iOS and Android App. How can I handle this event?

This is my ionic info:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.4
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.3.0
    npm        : 5.7.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```
I wrap my code in a service so I need to return a promise with success or error. Since cancel doesn't trigger anything, I am unable to complete it when user cancels the image selection from album. 

Is it possible to add this please? May I ask how long it might take to add this in?

Thank you so much for this awesome plugin. I love the fact that you can also select camera from the image picker which is really great.

Thanks,
Neel.

**Comment by giantss** [comment]
I have a try when I'm free, and I've been very busy recently. very sorry.

**Comment by Mr-Anonymous** [comment]
I understand. Thank you @giantss This will be very helpful especially when the controller is waiting for a promise after the picker completes it action with a success or error. When I change the logic in my controller as a way around this limitation where nothing is returned, it breaks the UI. Hopefully you get time to add this soon. Thanks again.

**Comment by giantss** [comment]
#58

**Comment by lovelyelfpop** [comment]
The latest version 1.1.3, error callback is available, but only for android. It's coming soon for ios. 
Pull requests are welcome.

**Comment by lovelyelfpop** [comment]
Error callback is triggered for ios as well when cancelled
