### ISSUE TITLE
Does it select Video as well?

### ISSUE THREAD

**Issue by Mr-Anonymous** [giantss/cordova-plugin-ImagePicker#54]
Is this plugin only for selecting Images or does it select Videos from Album as well? I only need images to be selected and in other plugins I usually need to add an option like:  

```
encodingType: Camera.EncodingType.JPEG,
mediaType: Camera.MediaType.PICTURE,
```

Do I need any setting like that for this plugin or it only lists and selects images only as default?

**Comment by giantss** [comment]
The plugin only supports picture selection

**Comment by Mr-Anonymous** [comment]
Thats perfect. I only need it for pictures so this is perfect.
