### ISSUE TITLE
Uploaded Image Quality is very poor

### ISSUE THREAD

**Issue by Mr-Anonymous** [giantss/cordova-plugin-ImagePicker#55]
I tested this from iOS so far. When I upload an image from Album, the uploaded image quality is very poor. I even tried these:

1. added `quality: 100` to options

2. Selected "Full image" when selecting images from Camera Roll

3. The results log shows filepath as:

```
"/Users/me/Library/Developer/CoreSimulator/Devices/D53A2E22-A48F-470D-A1A4-BA3C2F992FE4/data/Containers/Data/Application/BA666A51-B3FF-47EF-BA03-4CA3AE59BA54/Documents/iIMG_0002.jpg"
```
After the image is selected, I pass the above fileURI and upload to server using File Transfer plugin. It appears only the thumbnail quality of the image is uploaded and not the high quality image from Phone Album.

How can I fix this please?

**Comment by giantss** [comment]
Will this happen every time? Can you provide a working environment?

**Comment by Mr-Anonymous** [comment]
Hi @giantss 

Yes. This happens everytime. Unfortunately I cant provide a working environment but I will try and give more info if it  helps.

1. I tested this by launching the App from iPhone Simulator in my Macbook with iPhone X as target device and also from a real iPhone 7 device.

2. When I replace the plugin to Telerik Image Picker, the same image is getting uploaded in the right resolution.

3. The image is poor quality even when `quality` is set to 100. Also the upload is really quick and it appears it is uploading the thumbnail of that picture instead of the Full image.

Screenshot of Image Uploading using `giantss/cordova-plugin-ImagePicker`:

<img width="376" alt="giantss_image_picker_gallery" src="https://user-images.githubusercontent.com/8770270/39394154-071e8b60-4aec-11e8-89ff-b8d2302de5e4.png">
<img width="380" alt="screen shot 2018-04-28 at 1 39 59 pm" src="https://user-images.githubusercontent.com/8770270/39394141-c4e168ee-4aeb-11e8-886f-cc9879497f1d.png">
<img width="385" alt="giantss_imagepicker_gallery_preview" src="https://user-images.githubusercontent.com/8770270/39394140-c4ade5fa-4aeb-11e8-9232-0eaf36bb7c6d.png">
<img width="1000" alt="console_of_image_picker_results" src="https://user-images.githubusercontent.com/8770270/39394137-c4144152-4aeb-11e8-9c1d-f95cc3f13efa.png">

Quality of the image after they are uploaded using File Transfer plugin:

<img width="201" alt="image_after_upload" src="https://user-images.githubusercontent.com/8770270/39394139-c47b363c-4aeb-11e8-88e4-52f3b170cbb7.png">

<img width="390" alt="image_view_after_upload" src="https://user-images.githubusercontent.com/8770270/39394138-c4493ccc-4aeb-11e8-9358-02d11cad23aa.png">

Quality of the image when uploaded using `Telerik-Verified-Plugins/ImagePicker` even when quality is set to 50:

<img width="195" alt="image_when_uploaded_from_telerik" src="https://user-images.githubusercontent.com/8770270/39394135-c3c9bb5a-4aeb-11e8-9be9-1fe29aae6cd9.png">
<img width="381" alt="image_preview_when_uploaded_from_telerik" src="https://user-images.githubusercontent.com/8770270/39394134-c3938404-4aeb-11e8-9e76-6d457b7efe12.png">

As you can see, the image that gets uploaded from this plugin seems to be the thumbnail image from the device library instead of source image. 

Hope this helps.

Thank you for looking into this.

**Comment by Mr-Anonymous** [comment]
And, this is my ionic info:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.4
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.3.0
    npm        : 5.7.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

And these are the plugins I have installed other than this Image Picker:
```
cordova-android-support-gradle-release 1.4.0 "cordova-android-support-gradle-release"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Comment by giantss** [comment]
#58

**Comment by lovelyelfpop** [comment]
Please upgrade to the latest version and try again
