### ISSUE TITLE
Does it work with Android 7

### ISSUE THREAD

**Issue by Mr-Anonymous** [giantss/cordova-plugin-ImagePicker#56]
Does this plugin work with Android 7 or should I be using 6.3.0 or 6.4.0?

**Comment by giantss** [comment]
如果使用的`cordova plugin add cordova-plugin-imagepicker-plus`安装的不能使用（不是我在维护），可以换`cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git`试试。

**Comment by giantss** [comment]
1，如果使用的`cordova plugin add cordova-plugin-imagepicker-plus`安装的不能使用（不是我本人在维护），可以换`cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git`安装试试。
2，提交新的issues的时候尽量提供详细点的信息，比如使用平台、系统版本、手机型号、现象描述等信息，如果能提供报错信息最好，感谢大家的支持。

**Comment by giantss** [comment]
#58

**Comment by lovelyelfpop** [comment]
@Mr-Anonymous Please upgrade this plugin in your cordova project.
