### ISSUE TITLE
android build 报错

### ISSUE THREAD

**Issue by lysuse** [giantss/cordova-plugin-ImagePicker#57]
AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored

**Comment by giantss** [comment]
你是用的什么命令安装的

**Comment by lovelyelfpop** [comment]
请使用 cordova-android-support-gradle-release 这个插件统一项目中的 Android Support 库版本：

`$ cordova plugin add cordova-android-support-gradle-release  --variable ANDROID_SUPPORT_VERSION={required version}`
其中{required version} 值为类似 25.+，26.+，27.+ 这种。
