### ISSUE TITLE
cordova-android@6.4.0 build 失败，7.0.0正常

### ISSUE THREAD

**Issue by lg970044** [giantss/cordova-plugin-ImagePicker#61]
:CordovaLib:compileReleaseJavaWithJavacע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣

:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease
:compileReleaseJavaWithJavacD:\gc_app\platforms\android\src\com\giants\imagepicker\adapter\ImageFolderAdapter.java:59: ����: -source 1.6 �в�֧�� diamond �����
        else imageFolders = new ArrayList<>();
                                          ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
D:\gc_app\platforms\android\src\com\giants\imagepicker\adapter\ImageGridAdapter.java:49: ����: -source 1.6 �в�֧�� diamond �����
    private ArrayList<ImageItem> images = new ArrayList<>();       //��ǰ��Ҫ��ʾ�����е�ͼƬ����
                                                        ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
D:\gc_app\platforms\android\src\com\giants\imagepicker\adapter\ImagePageAdapter.java:32: ����: -source 1.6 �в�֧�� diamond �����
    private ArrayList<ImageItem> images = new ArrayList<>();
                                                        ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
D:\gc_app\platforms\android\src\com\giants\imagepicker\adapter\ImageRecyclerAdapter.java:71: ����: -source 1.6 �в�֧�� diamond �����
        if (images == null || images.size() == 0) this.images = new ArrayList<>();
                                                                              ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
D:\gc_app\platforms\android\src\com\giants\imagepicker\DataHolder.java:35: ����: -source 1.6 �в�֧�� diamond �����
        data = new HashMap<>();
                           ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
D:\gc_app\platforms\android\src\com\giants\imagepicker\ImageDataSource.java:37: ����: -source 1.6 �в�֧�� diamond �����
    private ArrayList<ImageFolder> imageFolders = new ArrayList<>();   //���е�ͼƬ�ļ���
                                                                ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
D:\gc_app\platforms\android\src\com\giants\imagepicker\ImagePicker.java:76: ����: -source 1.6 �в�֧�� diamond �����
    private ArrayList<ImageItem> mSelectedImages = new ArrayList<>();   //ѡ�е�ͼƬ����
                                                                 ^
  (��ʹ�� -source 7 ����߰汾������ diamond �����)
7 ������
 FAILED

FAILURE: Build failed with an exception.

**Comment by lovelyelfpop** [comment]
都是乱码 @lg970044

**Comment by lg970044** [comment]
JDK=1.8.0_131

后来，我用Android Studio导入platform下面的项目，编译时提示的错误信息和上面类似的几段，只不过没乱码：
source 1.6 中不支持 diamond 运算符

对应上面乱码的部分
:compileReleaseJavaWithJavacD:\gc_app\platforms\android\src\com\giants\imagepicker\adapter\ImageFolderAdapter.java:59: ����: -source 1.6 �в�֧�� diamond �����

**Comment by lg970044** [comment]
已找到解决办法，修改platform\android\build.gradle
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_6
    targetCompatibility JavaVersion.VERSION_1_6
}

改成

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

再build就正常了

**Comment by lovelyelfpop** [comment]
更新 v1.1.3 再看看
