### ISSUE TITLE
压缩图片时丢弃了图片exif信息，那些设置了拍摄方向图片显示时应该是竖的变成横向

### ISSUE THREAD

**Issue by lg970044** [giantss/cordova-plugin-ImagePicker#62]
压缩图片时丢弃了图片exif信息，没有了 Orientation | 拍摄方向 参数，使得有拍摄方向的图片显示错误

**Comment by lovelyelfpop** [comment]
压缩之后的图已经是调整过方向了的，我测试没这个问题，不管是限定宽高、还是自动压缩。
用的几个压缩库都处理过图片方向的

你可以把有问题的图片发上来。
