### ISSUE TITLE
ionic3可以直接用吗？

### ISSUE THREAD

**Issue by 519818538** [giantss/cordova-plugin-ImagePicker#7]
ionic3可以直接用吗？

**Comment by giantss** [comment]
ionic3没接触过，ionic3是做ui，理论上是可以的

**Comment by GuoDapeng** [comment]
ionic 3.7.0 上进行了测试，是可以用的。

安装方法：
ionic cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git

安装时候记得对照文档，把准备工作做好。
