### ISSUE TITLE
请问我想在拍照或选择图片后增加涂鸦功能，应该在插件什么部分修改

### ISSUE THREAD

**Issue by wxbwjt** [giantss/cordova-plugin-ImagePicker#70]
因为没有太多时间去学习整个基础，只能先求助您看看直接在什么位置下手看代码比较容易理解，或者希望您能给出别的建议，谢谢

**Comment by giantss** [comment]
首先你要实现的图片编辑（涂鸦）功能，android、ios两端都是需要在原生代码中去实现的。你可以fork一个到自己的仓库里面，然后实现该功能，如果没有原生基础这个功能对你来说是一个比较大的挑战，涉及到的知识面很广的。
[ios参考](https://github.com/whbalzac/WHStoryMaker)
[android参考](https://github.com/jarlen/PhotoEdit)

**Comment by wxbwjt** [comment]
多谢百忙之中抽空答复

**Comment by wxbwjt** [comment]
大大您好，我根据你给的意见，尝试往安卓部分集成了涂鸦的部分，但是获得保存的图片以后，应该怎么样去刷新预览和图库，因为每次涂鸦结束后，我退回到多选界面， 新增的图片都没读取到

**Comment by giantss** [comment]
不好意思，最近比较忙。我现在工作没有再使用cordova了。嗯，插件代码里面有裁剪功能，没有开放出来。所以还需要像你这样优秀的开发者，去实现部分功能，然后PR上来给更多的开发者提供帮助。🤝

**Comment by wxbwjt** [comment]
好的，还是要感谢您提供的帮助，祝您工作顺利
