### ISSUE TITLE
是否支持点击缩略图浏览大图

### ISSUE THREAD

**Issue by canghai0902** [giantss/cordova-plugin-ImagePicker#71]
是否支持点击缩略图浏览大图,现在用官网的photoView插件会报 com.android.build.api.transform.TransformException: java.util.zip.ZipException
 duplicate entry: uk/co/senab/photoview/BuildConfig.class
的错误,看了下,应该是PhotoView与ImagePicker的jar包冲突了

**Comment by giantss** [comment]
jar包冲突是难免的，需要自行解决哦
