### ISSUE TITLE
Cordova build 时CompressHelper  Could not resolve com.github.nanchen2251:报错

### ISSUE THREAD

**Issue by SeaLi** [giantss/cordova-plugin-ImagePicker#76]
ould not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.nanchen2251:CompressHelper:1.0.+.
  Required by:
      project :app
   > Could not resolve com.github.nanchen2251:CompressHelper:1.0.+.
      > Failed to list versions for com.github.nanchen2251:CompressHelper.
         > Unable to load Maven meta-data from https://jitpack.io/com/github/nanchen2251/CompressHelper/maven-metadata.xml.
            > Could not HEAD 'https://jitpack.io/com/github/nanchen2251/CompressHelper/maven-metadata.xml'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested tar
get

**Comment by lovelyelfpop** [comment]
网络问题你懂的
