### ISSUE TITLE
安装成功了，为什么返回的图片路径，就是path字段，放到img标签里显示不出来

### ISSUE THREAD

**Issue by iminfx** [giantss/cordova-plugin-ImagePicker#78]
安装成功了，为什么返回的图片路径，就是path字段，放到img标签里显示不出来

**Comment by lovelyelfpop** [comment]
加上 file:// 前缀看看。
ios 吗？wkwebview？wkwebview 只能显示 tmp 目录下的 图片，也要把图片移动到这里。

**Comment by lovelyelfpop** [comment]
应该是你 ionic 的问题，http下不允许显示 file:// 地址

**Comment by crayon1127** [comment]
这个问题还存在，请问有解决方案吗

**Comment by lovelyelfpop** [comment]
@crayon1127 这是属于ionic的问题，即使是camera插件，一样也有这个问题。

**Comment by xiandanchaorenguagua** [comment]
有解决吗？问题依然存在

**Comment by lovelyelfpop** [comment]
@xiandanchaorenguagua 

# Cordova + iOS
1、cordova-ios@5及以下 (cordova@9及以下)
因为 wkwebview 只能展示 `file:///private/var/mobile/Containers/Data/Application/{UUID}/tmp/` 下的图片(不知道为什么)，所以没办法，只能升级到高版本 cordova(看2)

2、cordova-ios@6及以上 (cordova@10及以上)
用 `window.WkWebView.convertFilePath('file:///var/mobile/.......................')` 可以转为
`app://localhost/_app_file_/var/mobile/.........` 的地址，就可以在页面上展示了，其中 `app://localhost` 是 `config.xml` 里面配置的
```xml
<preference name="scheme" value="app">
<preference name="hostname" value="localhost">
```

# Cordova + Android
1、cordova-android@9及以下(cordova@10及以下) 
页面可以直接展示 `file://.....` 

2、cordova-android@10及以上 (cordova@11及以上) 
**注意：本插件不适于这个版本的 cordova(因为不支持 android.support 库必须要 androidx)，本插件没有使用 androidx**
用下面的方法转换地址后，才可以在页面展示
```javascript
window.resolveLocalFileSystemURL('file:///data/user/0/com.xxx.yyy/files/......', function (fileEntry) {
    console.log(fileEntry.toURL());
    // 得到的结果形如 https://localhost/__cdvfile_files_/......，可以展示在页面上
}, function(err) {
    console.log(err)
});
```
上面的 `https://localhost` 是 `config.xml` 里面配置的
```xml
<preference name="scheme" value="https">
<preference name="hostname" value="localhost">
```


# ionic
我没用过，上面有人说用 normalizeURL()方法 转下地址，可以试下

**Comment by xiandanchaorenguagua** [comment]
@lovelyelfpop 
感谢回复。但我使用你的方法并没什么用，
window.resolveLocalFileSystemURL('file:///data/user/0/io.cordova.hellocordova/cache/ImagePicker/face_female2.jpeg', function (fileEntry) {
    console.log(fileEntry.toURL());
}, function(err) {
    console.log(err)
});
config.xml也做了相关配置，输出的地址依旧是：'file:///data/user/0/io.cordova.hellocordova/cache/ImagePicker/face_female2.jpeg'

**Comment by lovelyelfpop** [comment]
@xiandanchaorenguagua 如果你的 `index.html` 是 `file://android_assets/www/index.html` 访问的，`file:///data/user/0/io.cordova.hellocordova/cache/ImagePicker/face_female2.jpeg` 就可以直接展示。

需要利用 `window.resolveLocalFileSystemURL` 转换地址的是 cordova-android@10+，而我这个插件没适配 cordova-android@10+

**Comment by xiandanchaorenguagua** [comment]
@lovelyelfpop 
我们的index.html是放服务器上通过https://访问的。有办法从h5解决图片显示的问题吗？

**Comment by lovelyelfpop** [comment]
@xiandanchaorenguagua 
对于**安卓**，`https://` 加载的网页，默认只能显示https的图片。

解决方法：
1、如果要显示其它协议的图片，必须要**开启 webview 的 MixedContentMode**。
方法：在`platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebViewEngine.java`类内
增加`settings.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);`
![1](https://user-images.githubusercontent.com/5656924/173298948-5183d276-749d-438d-ae8b-c6b5d7dca8e5.png)


2、不过即使是开启了 MixedContentMode，webview 也不能显示 `file://`的图片，会报错 `Not allowed to load local resource`，需要将 `file://` 地址用 `window.resolveLocalFileSystemURL()` **转为** `cdvfile://` **协议的地址**，再展示。
```
window.resolveLocalFileSystemURL('file:///data/user/0/com.xxx.yyy/files/1111.jpg', function (file) {
    console.log(file.toInternalURL());
    // 得到形如 cdvfile://localhost/files/1111.jpg 的地址 (仅限cordova-android@9及以下，即cordova@10及以下)
}, function(err) {
    console.log(err)
});
```

3、另外，还需要在 html 的 `<meta http-equiv="Content-Security-Policy"` (**内容安全策略**) 上**补充** `cdvfile:`。如下是我的 `meta` 设置
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' blob: data: cdvfile: 'unsafe-eval' *; style-src 'self' 'unsafe-inline' *; script-src 'self' cdvfile: 'unsafe-inline' 'unsafe-eval' *; connect-src 'self' blob: cdvfile: ws: wss: *;">
```

**Comment by xiandanchaorenguagua** [comment]
@lovelyelfpop 
感谢耐心解答。
还是会报错，如下：
`GET cdvfile://localhost/cache/ImagePicker/IMG_20220607_102046.jpeg net::ERR_UNKNOWN_URL_SCHEME`
不知道是不是跟我版本有关系，我使用的AndroidX，cordova@11.0.0，cordova-android@4.0.2
换了一种解决方案成功了：
`  function getPics() {
    ImagePicker.getPictures(function(result) {
        for (let i = 0; i < result.images.length; i++) {
            readImgFile(result.images[i].uri, (res) => {
               // 这里输出base64
               console.log(res)
            })
        }
      }, function(err) {
          console.log(err);
      }, {
          maximumImagesCount : 9,
          width : 1920,
          height : 1440,
          quality : 100
      });
    }

    function readImgFile(uri, callBack){
        window.resolveLocalFileSystemURL(uri, (fileEntry) => {
                fileEntry.file(file => {
                    console.log(file);
                    // 读取文件内容
                    const reader = new FileReader()
                    // 文件编码成DataURL 
                    reader.readAsDataURL(file)
                    // 文件读取完毕，成功/失败都会触发
                    reader.onloadend = (data) => {
                        var imgBase64Data = data.target.result;
                        callBack(imgBase64Data)
                    }
                }, (error) => {
                    console.log(error)
                    reject(error)
                })
            })
    }`

**Comment by xiandanchaorenguagua** [comment]
@lovelyelfpop 
感谢耐心解答。
还是会报错，如下：
`GET cdvfile://localhost/cache/ImagePicker/IMG_20220607_102046.jpeg net::ERR_UNKNOWN_URL_SCHEME`
不知道是不是跟我版本有关系，我使用的AndroidX，cordova@11.0.0，cordova-android@4.0.2
换了一种解决方案成功了：
` function getPics() {
    ImagePicker.getPictures(function(result) {
        for (let i = 0; i < result.images.length; i++) {
            readImgFile(result.images[i].uri, (res) => {
               // 这里输出base64
               console.log(res)
            })
        }
      }, function(err) {
          console.log(err);
      }, {
          maximumImagesCount : 9,
          width : 1920,
          height : 1440,
          quality : 100
      });
    }

    function readImgFile(uri, callBack){
        window.resolveLocalFileSystemURL(uri, (fileEntry) => {
                fileEntry.file(file => {
                    console.log(file);
                    // 读取文件内容
                    const reader = new FileReader()
                    // 文件编码成DataURL 
                    reader.readAsDataURL(file)
                    // 文件读取完毕，成功/失败都会触发
                    reader.onloadend = (data) => {
                        var imgBase64Data = data.target.result;
                        callBack(imgBase64Data)
                    }
                }, (error) => {
                    console.log(error)
                    reject(error)
                })
            })
    }`

**Comment by lovelyelfpop** [comment]
@xiandanchaorenguagua 
读取文件到内存 然后转DataURL的方式太占运存，不好。

为什么你的 cordova 版本11最新，但是 cordova-android 却用4.0.2那么低的版本?
还有，你的 cordova-plugin-file 插件是什么版本？

**Comment by xiandanchaorenguagua** [comment]
@lovelyelfpop 我们项目比较老了，cordova 11主要是用了AndroidX，我改了源码全都映射成AndroidX了，
映射表：
https://developer.android.google.cn/jetpack/androidx/migrate/class-mappings?hl=zh-cn
cordova-plugin-file的版本：1.3.3

**Comment by lovelyelfpop** [comment]
@xiandanchaorenguagua Cordova@11 中默认 Cordova-Android@10 才强制 AndroidX，如果是 Cordova-Android@4.0.2 应该不需要 AndroidX 吧。
