### ISSUE TITLE
Mac 使用imagePicker 进行build android 遇到的 android.support.v4.app问题及解决：

### ISSUE THREAD

**Issue by sunchao0427** [giantss/cordova-plugin-ImagePicker#79]
## 问题完整描述如下：

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.FragmentTransitionCompat21$1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

## 解决方法：
在安装的imagepicker插件的plugins/cordova-plugin-imagepicker/src/android/imagepicker.gradle 文件中，找到dependencies条目下的项，在implementation 'com.android.support:appcompat-v7:+'的下一行添加：implementation 'com.android.support:support-v4:+'   然后 cordova plugin save(保存修改)  cordova platform rm android (删除平台)  cordova platform add android(添加平台)    这样该问题得到很好的解决

## 建议
 添加v4 依赖。

**Comment by lovelyelfpop** [comment]
已解决
