### ISSUE TITLE
ios 图片无法显示

### ISSUE THREAD

**Issue by zhaoleisam** [giantss/cordova-plugin-ImagePicker#80]
ios12.2  选择图片后，页面无法显示

**Comment by lovelyelfpop** [comment]
你是Ionic？还是说只有ios12.2不能显示？

**Comment by zhaoleisam** [comment]
Ionic3

**Comment by lovelyelfpop** [comment]
Ionic 内部启动了一个服务器，连 index.html都是 http://形式访问的，所以不能直接展示  file:// 路径的图片，你要把  file:// 转换成 http:// 地址

**Comment by lovelyelfpop** [comment]
如果你用的 cordova-plugin-ionic-webview，它有一个 convertFileSrc 方法

**Comment by zhaoleisam** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/22520663/58082887-7a8aef00-7bea-11e9-9127-5b3a60c7570a.png">

**Comment by lovelyelfpop** [comment]
inoic 我没用过，不清楚，你要研究下 cordova-plugin-ionic-webview
