### ISSUE TITLE
报错如下 Execution failed for task ':processDebugResources'.

### ISSUE THREAD

**Issue by wangren988888** [giantss/cordova-plugin-ImagePicker#81]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by wangren988888** [comment]
已经按照安卓注意事项中implementation => compile

**Comment by wangren988888** [comment]
Macos  cordova 7.x  cordova-Android@6.3.0。

**Comment by lovelyelfpop** [comment]
Android SDK Manager 更新SDK到 28，使用 cordova-android-support-gradle-release 统一 suppoer 库版本为28
