### ISSUE TITLE
cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git安装失败

### ISSUE THREAD

**Issue by yangandroidkang** [giantss/cordova-plugin-ImagePicker#85]
cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git安装失败
提示Failed to fetch plugin https://github.com/giantss/cordova-plugin-ImagePicker.get via registry.
Probably this is either a connection problem, or plugin spec is incorrect.

**Comment by lovelyelfpop** [comment]
网络问题
