### ISSUE TITLE
android getItemDecorationCount 报错

### ISSUE THREAD

**Issue by zhantewei2** [giantss/cordova-plugin-ImagePicker#86]
### android api25 
请使用
```
cordova plugin add https://github.com/giantss/cordova-plugin-ImagePicker.git#1.1.5
```
新版使用了`getItemDecorationCount `方法，只能在27.1.0以上工作。
这是我今天遇到到的坑，希望对别人有帮助。

**Comment by FWiner** [comment]
哎，我用26的库所以报错了

**Comment by lovelyelfpop** [comment]
用插件 https://github.com/dpa99c/cordova-android-support-gradle-release 统一 cordova 项目中 support 库的版本，我一直用 28的库
