### ISSUE TITLE
动态修改maximumImagesCount问题

### ISSUE THREAD

**Issue by liuqing024** [giantss/cordova-plugin-ImagePicker#87]
实现效果：随图片数量变化改变最大图片限制
let options = {
          maximumImagesCount: 3 - this.picArray.length,
          width: 1080,
          height: 1920,
          quality: 100
        }
window.ImagePicker.getPictures(
          function (results) {
            for (let i = 0; i < results.images.length; i++) {
              _this.picArray.push(results.images[i].uri)
            }
          },
          function (error) {
            console.log('Error: ' + error)
          },
          options
        )
问题：当图片数量为2时，限制图片数量为1，此时图片选择为单项，将图片删除，图片数量变为1，限制图片数量2，此时依然是单选，不能多选。

**Comment by liuqing024** [comment]
cordova-plugin-ImagePicker-master/src/android/module/ui/ImageGridActivity.java中
将
        if (imagePicker.getSelectLimit() == 0 || imagePicker.getSelectLimit() == 1) {
            imagePicker.setSelectLimit(1);
            imagePicker.setMultiMode(false);
        }

改为
        if (imagePicker.getSelectLimit() == 0 || imagePicker.getSelectLimit() == 1) {
            imagePicker.setSelectLimit(1);
            imagePicker.setMultiMode(false);
        } else {
        	imagePicker.setMultiMode(true);
        }

**Comment by dawdlerlibo** [comment]
我的问题是   在俩个页面  都有用这个组件
一个组件是maximumImagesCount:1

另一个是 maximumImagesCount:9

但是你先选maximumImagesCount:1 的话    后面那一个maximumImagesCount 也会 成为1

先选那个   9    的话呢    后面那个也会成为9

我已经照着  上面的办法弄了   没有效果

**Comment by yeyingjie** [comment]
> 我的问题是 在俩个页面 都有用这个组件
> 一个组件是maximumImagesCount:1
> 
> 另一个是 maximumImagesCount:9
> 
> 但是你先选maximumImagesCount:1 的话 后面那一个maximumImagesCount 也会 成为1
> 
> 先选那个 9 的话呢 后面那个也会成为9
> 
> 我已经照着 上面的办法弄了 没有效果
我和你是同样的问题，请问你解决了吗

**Comment by yeyingjie** [comment]
我遇到的问题和楼上一样，请问该如何解决

**Comment by liuqing024** [comment]
我的问题是一个页面里中图片剩余1个后，再删除不能多选图片，和你说的不是一个问题。




 
发件人： yeyingjie
发送时间： 2019-08-29 16:22
收件人： giantss/cordova-plugin-ImagePicker
抄送： liuqing024; Author
主题： Re: [giantss/cordova-plugin-ImagePicker] 动态修改maximumImagesCount问题 (#87)
我的问题是 在俩个页面 都有用这个组件
一个组件是maximumImagesCount:1
另一个是 maximumImagesCount:9
但是你先选maximumImagesCount:1 的话 后面那一个maximumImagesCount 也会 成为1
先选那个 9 的话呢 后面那个也会成为9
我已经照着 上面的办法弄了 没有效果
我和你是同样的问题，请问你解决了吗

**Comment by dawdlerlibo** [comment]
@liuqing024 我的那个问题按照上面的办法把那俩个文件都改了就可以了
