### ISSUE TITLE
cache location

### ISSUE THREAD

**Issue by hongnk** [giantss/cordova-plugin-ImagePicker#9]
on Android selecting image result is /data/user/0/[package_name]/cacheCompressHelper/IMG_xyz.jpeg
then call resolveLocalFileSystemURL but got error code 1 (not found).

I check in explorer also doesn't seem to find this cache location?

Other than that this plugin looks great.  Thank you.

**Comment by hongnk** [comment]
Ok this is not an issue. I found out that on android resolveLocalFileSystemURL doesn't work with full path.  Need to call resolveLocalFileSystemURL for cordova.file.applicationStorageDirectory then loop through the entries to find the cached image.  

It is mentioned in here: https://stackoverflow.com/questions/35192695/phonegap-cordova-for-android-file-plugin-error-code-1/35208599#35208599

The cache image is private to the application, so searching in explorer doesn't show it, unless the phone is rooted.

**Comment by F5F5** [comment]
@hongnk I have same problem，and I don't understand stackoverflow's answer，Can you show your read image file code in here？thank you very much！: )

**Comment by hongnk** [comment]
window.resolveLocalFileSystemURL(path, function (fileEntry) {
    fileEntry.file(function(file) {         
      cb(file)
    }, function() {
        alert('error');
    });
      
  }, function (e) {
      //window.alert("error: " + JSON.stringify(e));
      //on Android, need to loop
      var dirEntry = function (entry) {
        var dirReader = entry.createReader();
        dirReader.readEntries(
            function (entries) {
                Array.from(entries).forEach(function (n, i) {
                    if (n.isDirectory === true) `{`
                        if (n.nativeURL.indexOf('/cacheCompressHelper') > -1 || n.nativeURL.indexOf('/Documents') > -1) {
                          var dirReader2 = n.createReader();
                          dirReader2.readEntries(function(files) {
                              //found the target /res directory
                              Array.from(files).forEach(function (f, i) {
                                if(f.isFile && f.nativeURL.indexOf(path)>=0) {
                                  f.file(function(file) {         
                                    cb(file)
                                  }, function() {
                                      alert('error');
                                  });
                                }
                              })
                            })
                            return false; //no need to iterate more
                        } else {
                            // Recursive -- call back into this subdirectory
                            dirEntry(n);
                        }
                    }
                });

            },
            function (error) {
                console.log("readEntries error: " + error.code);
            }
        );
      };

      var dirError = function (error) {
          console.log("getDirectory error: " + error.code);
      };

      window.resolveLocalFileSystemURL(cordova.file.applicationStorageDirectory, dirEntry, dirError);
  });
}

**Comment by giantss** [comment]
oh,I didn't have such a problem.
