### ISSUE TITLE
今天突然打包不能用了，移除这个插件就可以了

### ISSUE THREAD

**Issue by cuidong626** [giantss/cordova-plugin-ImagePicker#90]
今天突然打包不能用了，移除这个插件就可以了。
这个是什么原因啊？这个插件用了好久一直没事，今天突然打包报错

**Comment by ducp123** [comment]
是啊，突然就打包不了呢

**Comment by kingheart123** [comment]
遇到了同样的问题(AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android')，我做了以下处理后就好了。

修改plugins/cordova-plugin-imagepicker/src/android/imagepicker.gradle文件：
**把 'com.github.bumptech.glide:glide:4.+'
修改为 'com.github.bumptech.glide:glide:4.9.0'**

初步分析是glide这个依赖在9.19这天发布了新版本4.10.0，该版本要用Android SDK 28构建，否则就出现异常了。

**Comment by ducp123** [comment]
OK，我试试，感谢！我现在的处理方式是移除这个插件，换了一个，我也觉得是依赖包的问题

在 2019-09-20 14:33:08，"kingheart123" <notifications@github.com> 写道：


遇到了同样的问题(AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android')，我做了以下处理后就好了。

修改plugins/cordova-plugin-imagepicker/src/android/imagepicker.gradle文件：
把 'com.github.bumptech.glide:glide:4.+'
修改为 'com.github.bumptech.glide:glide:4.9.0'

初步分析是glide这个依赖在9.19这天发布了新版本4.10.0，该版本要用Android SDK 28构建，否则就出现异常了。
