### ISSUE TITLE
iPhone 11 压缩图片时间过长 compressed photos size

### ISSUE THREAD

**Issue by JianhuisHuang** [giantss/cordova-plugin-ImagePicker#94]
在iPhone 11 选完图片后，压缩时间过长，居然比在iPhone 6s或者iPhone 7P还长 compressed photos size，请问有知道是什么问题和解决办法吗？谢谢

**Comment by lovelyelfpop** [comment]
我们没iPhone11，你调试下看看哪里慢

**Comment by JianhuisHuang** [comment]
@lovelyelfpop  `Luban-iOS image data size after compressed` 在这里，估计是Luban-iOS compressed 的问题，只有在iPhone 11 或者iPhone 11 Pro 时间更长，iPhone 6 7 8 都正常

**Comment by lovelyelfpop** [comment]
试下刚刚发布的 1.2.2 版本

**Comment by JianhuisHuang** [comment]
> 试下刚刚发布的 1.2.2 版本

试了，好像没有多大的提升

**Comment by zero1988** [comment]
> > 试下刚刚发布的 1.2.2 版本
> 
> 试了，好像没有多大的提升

麻烦你把你的测试图片发给我试试看，我这边用模拟器测试的貌似没啥问题，1099789021@qq.com

**Comment by JianhuisHuang** [comment]
> > > 试下刚刚发布的 1.2.2 版本
> > 
> > 
> > 试了，好像没有多大的提升
> 
> 麻烦你把你的测试图片发给我试试看，我这边用模拟器测试的貌似没啥问题，[1099789021@qq.com](mailto:1099789021@qq.com)

我刚刚又测了一遍，1.2.1 中log 出现好多个 `All finished`，要target到最后一个，才算真正完成压缩，而1.2.2中，log只出现一个`All finished`，此时已经是真正的完成了压缩，所以之前我计算的时间有误差，现在看来确实是提升了不少
