### ISSUE TITLE
IOS13版本在点击完成完成按钮时闪退

### ISSUE THREAD

**Issue by yangshuyi** [giantss/cordova-plugin-ImagePicker#95]
在IOS13版本上有该问题，android和其他ios版本正常，能帮忙找下原因么

**Comment by lovelyelfpop** [comment]
ios什么版本，我们没遇到闪退

**Comment by yangshuyi** [comment]
我的微信号是 superyang_xp 方便的话 我加你一下，和你说一下具体情况
iOS版本是13，一般在相册里选了超过10张照片后，点击完成会闪退，猜测是不是内存溢出问题
有没有地方能看出错日志？

**Comment by yangshuyi** [comment]
版本是 13.2.2，

**Comment by lovelyelfpop** [comment]
试下刚刚发布的 1.2.2 版本

**Comment by yangshuyi** [comment]
日志信息

0x10e23a700 - ScriptedAnimationController::removeThrottlingReason(VisuallyIdle) -> <private>

Received memory warning.

Memory pressure relief: Total: res = 74661888/74678272/16384, res+swap = 122389504/122405888/16384

Received memory pressure event 4 vm pressure 1

**Comment by yangshuyi** [comment]
请帮忙看下是不是 tzimagepickercontroller 的问题。。。

**Comment by yangshuyi** [comment]
刚看到你的回复，谢谢，我下周一测试下

**Comment by yangshuyi** [comment]
问题解决了，再次谢谢你。
Github上没有donate的功能，能给我个微信账号么，交个朋友吧。

**Comment by lovelyelfpop** [comment]
捐助就不用了，项目所有者不是我，我只是参与。可以加群273613165
